# Generated by Django 5.2.3 on 2025-06-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0002_chapter_remove_topics_chapter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
