# Generated by Django 5.2.3 on 2025-06-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0003_delete_userprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='content',
            new_name='rendered_content',
        ),
    ]
