# Generated by Django 5.2.3 on 2025-06-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0004_rename_content_topic_rendered_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='rendered_content',
            new_name='content',
        ),
    ]
