# Generated by Django 5.2.3 on 2025-06-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0005_rename_rendered_content_topic_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
        migrations.AddField(
            model_name='topic',
            name='rendered_content',
            field=models.TextField(default='', editable=False),
        ),
    ]
